definitions:
  errorno.ErrorResponse:
    properties:
      code:
        type: integer
      full_text:
        type: string
      message:
        type: string
    type: object
  model.Record:
    properties:
      data: {}
      key:
        type: string
      type:
        description: |-
          Record Type:
          * RAW - []byte payload
          * HRECORD - JSON payload
        enum:
        - RAW
        - HRECORD
        type: string
    required:
    - data
    - key
    - type
    type: object
  model.RecordId:
    properties:
      batch_id:
        type: integer
      batch_index:
        type: integer
      shard_id:
        type: integer
    type: object
  model.Stream:
    properties:
      backlog_duration:
        type: integer
      replication_factor:
        type: integer
      stream_name:
        type: string
    required:
    - stream_name
    type: object
  model.Subscription:
    properties:
      ack_timeout_seconds:
        type: integer
      max_unacked_records:
        type: integer
      stream_name:
        type: string
      subscription_id:
        type: string
    required:
    - stream_name
    - subscription_id
    type: object
  model.TableResult:
    properties:
      headers:
        items:
          type: string
        type: array
      value:
        items:
          additionalProperties:
            type: string
          type: object
        type: array
    type: object
info:
  contact: {}
  description: http server for HStreamDB
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: HStreamDB-Server API
  version: 0.1.0
paths:
  /v1/cluster/stats:
    get:
      operationId: statsGet
      parameters:
      - description: Category
        in: query
        name: category
        required: true
        type: string
      - description: Metrics
        in: query
        name: metrics
        required: true
        type: string
      - collectionFormat: multi
        description: Interval collection
        in: query
        items:
          type: string
        name: interval
        type: array
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TableResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Get cluster stats
  /v1/cluster/status:
    get:
      operationId: statusGet
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TableResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Get server status of the cluster
  /v1/stats/append/bytes:
    get:
      operationId: streamAppendsStats
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TableResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Get rate of bytes successfully written to the stream.
  /v1/stats/append/failed:
    get:
      operationId: failedAppendStats
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TableResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Get total number of failed append request of a stream
  /v1/stats/append/records:
    get:
      operationId: appendInRecordStats
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TableResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Get rate of records successfully written to the stream
  /v1/stats/append/success:
    get:
      operationId: totalAppendStats
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TableResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Get total number of success append requests of a stream
  /v1/stats/histogram/server_append_latency:
    get:
      operationId: appendLatency
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TableResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Get stream append latency stats
  /v1/stats/histogram/server_append_request_latency:
    get:
      operationId: appendRequestLatency
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TableResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Get stream append request latency stats
  /v1/stats/send/records:
    get:
      operationId: sendOutRecords
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TableResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Get rate of records successfully sent by the server per subscription
  /v1/stats/sends/bytes:
    get:
      operationId: subscriptionSendsStats
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TableResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Get rate of bytes sent by the server per subscription
  /v1/streams/:
    get:
      operationId: streamList
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Stream'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: List all streams in the cluster
    post:
      operationId: streamCreate
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.Stream'
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Create a stream
  /v1/streams/{streamName}:
    delete:
      operationId: streamDelete
      parameters:
      - description: Stream Name
        in: path
        name: streamName
        required: true
        type: string
      responses:
        "200":
          description: ok
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Delete specific stream by streamName
    get:
      operationId: streamGet
      parameters:
      - description: Stream name
        in: path
        name: streamName
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Stream'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Get specific stream by streamName
    post:
      operationId: streamAppend
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.Record'
      - description: Stream name
        in: path
        name: streamName
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.RecordId'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Append record to specific stream
  /v1/subscriptions/:
    get:
      operationId: subscriptionList
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Subscription'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: List all subscriptions in the cluster
    post:
      operationId: subscriptionCreate
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.Subscription'
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Create a subscription
  /v1/subscriptions/{subId}:
    delete:
      operationId: subscriptionDelete
      parameters:
      - description: Subscription Id
        in: path
        name: subId
        required: true
        type: string
      responses:
        "200":
          description: ok
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Delete specific subscription by subscription id
    get:
      operationId: subscriptionGet
      parameters:
      - description: Subscription Id
        in: path
        name: subId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Subscription'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Get specific subscription by subscription id
swagger: "2.0"
