definitions:
  errorno.ErrorResponse:
    properties:
      code:
        type: integer
      full_text:
        type: string
      message:
        type: string
    type: object
  model.Record:
    properties:
      data: {}
      key:
        type: string
      type:
        description: |-
          Record Type:
          * RAW - []byte payload
          * HRECORD - JSON payload
        enum:
        - RAW
        - HRECORD
        type: string
    required:
    - data
    - key
    - type
    type: object
  model.RecordId:
    properties:
      batch_id:
        type: integer
      batch_index:
        type: integer
      shard_id:
        type: integer
    type: object
  model.Stream:
    properties:
      backlog_duration:
        type: integer
      replication_factor:
        type: integer
      stream_name:
        type: string
    required:
    - stream_name
    type: object
  model.Subscription:
    properties:
      ack_timeout_seconds:
        type: integer
      streamName:
        type: string
      subscription_id:
        type: string
    required:
    - streamName
    - subscription_id
    type: object
info:
  contact: {}
  description: http server for HStreamDB
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: HStreamDB-Server API
  version: 0.1.0
paths:
  /v1/streams/:
    get:
      operationId: streamList
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Stream'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: List all streams in the cluster
    post:
      operationId: streamCreate
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.Stream'
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Create a stream
  /v1/streams/{streamName}:
    delete:
      operationId: streamDelete
      parameters:
      - description: Stream Name
        in: path
        name: streamName
        required: true
        type: string
      responses:
        "200":
          description: ok
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Delete specific stream by streamName
    get:
      operationId: streamGet
      parameters:
      - description: Stream name
        in: path
        name: streamName
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Stream'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Get specific stream by streamName
    post:
      operationId: streamAppend
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.Record'
      - description: Stream name
        in: path
        name: streamName
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.RecordId'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Append record to specific stream
  /v1/subscriptions/:
    get:
      operationId: subscriptionList
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Subscription'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: List all subscriptions in the cluster
    post:
      operationId: subscriptionCreate
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.Subscription'
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Create a subscription
  /v1/subscriptions/{subId}:
    delete:
      operationId: subscriptionDelete
      parameters:
      - description: Subscription Id
        in: path
        name: subId
        required: true
        type: string
      responses:
        "200":
          description: ok
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Delete specific subscription by subscription id
    get:
      operationId: subscriptionGet
      parameters:
      - description: Subscription Id
        in: path
        name: subId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Subscription'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorno.ErrorResponse'
      summary: Get specific subscription by subscription id
swagger: "2.0"
