name: release

on:
  push:

env:
  IMAGE_NAME: hstreamdb/http-server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push release image
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker build . -t ${IMAGE_NAME}:${GITHUB_REF#refs/*/}
          docker push ${IMAGE_NAME}:${GITHUB_REF#refs/*/}

      - name: Build & Push latest image
        if: "${{ !startsWith(github.ref, 'refs/tags/v') }}"
        run: |
          docker build . -t ${IMAGE_NAME}:latest
          docker push ${IMAGE_NAME}:latest
